spring:
  profiles: local-dev
  data:
      mongodb:
        database: notice
        host: localhost
        port: 27017

  datasource:
    url: jdbc:h2:~/naver-hackday;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=true
    driver-class-name: org.h2.Driver
    username: sa
    password:
    platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

fileupload:
  rootdir: /Users/wheejuni/Documents/testfiles

---
spring:
  profiles: mongo
  data:
    mongodb:
      port: 27017
      database: notice
      host: localhost

